In [2]:
import torch

In [5]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
x.shape


torch.Size([12])

In [17]:
x.numel()


12

In [19]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [36]:
x2=torch.arange(12*2)
x2 = x2.reshape(3,2,4)
x2.reshape(-1,4,2)
x2

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])

x2=torch.arange(12*2)  ()里可以直接进行运算   三维三个量得给2个 即自动计算张量改变成n维时候给n-1个已知量

In [40]:
torch.ones((2,3,4))#或torch.zeros 但是没有twos

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [20]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [ ]:
X==Y

In [26]:
X = torch.arange(24, dtype=torch.float32).reshape((2,3,4))
Y = torch.tensor([[[2.0, 1, 4, 3], [1, 2, 3, 4],[4, 3, 2, 1]],
                 [[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]])
torch.cat((X, Y), dim=1),torch.cat((X, Y), dim=2)

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [ 2.,  1.,  4.,  3.],
          [ 1.,  2.,  3.,  4.],
          [ 4.,  3.,  2.,  1.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.],
          [ 2.,  1.,  4.,  3.],
          [ 1.,  2.,  3.,  4.],
          [ 4.,  3.,  2.,  1.]]]),
 tensor([[[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
          [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
          [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]],
 
         [[12., 13., 14., 15.,  2.,  1.,  4.,  3.],
          [16., 17., 18., 19.,  1.,  2.,  3.,  4.],
          [20., 21., 22., 23.,  4.,  3.,  2.,  1.]]]))

对于维数为3的张量
dim=0 不提前切开  直接按n个三维的顺叠
dim=1 提前切开1次  分成n个二维区域堆叠
dim=2 提前切开2次  分成n个一维区域堆叠
