In [1]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price,sale,like-value\n')  # 列名
    f.write('NA,Pave,127500,NA,4.5\n')  # 每行表示一个数据样本
    f.write('3,NA,106000,yes,4.5\n')
    f.write('5.0,NA,178100,no,3.5\n')
    f.write('4,NA,140000,yes,2\n')
    f.write('NA,Pave,2000,yes,2.8\n')

自行更改行列

In [2]:

import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price sale  like-value
0       NaN  Pave  127500  NaN         4.5
1       3.0   NaN  106000  yes         4.5
2       5.0   NaN  178100   no         3.5
3       4.0   NaN  140000  yes         2.0
4       NaN  Pave    2000  yes         2.8


In [3]:
#import numpy as np 
# inputs = data.iloc[:, np.r_[0:2, 3:5]] 
inputs, outputs = data.iloc[:, [0,1,3,4]], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley sale  like-value
0       4.0  Pave  NaN         4.5
1       3.0   NaN  yes         4.5
2       5.0   NaN   no         3.5
3       4.0   NaN  yes         2.0
4       4.0  Pave  yes         2.8


选取行列还可以用  inputs = data.iloc[:, np.r_[0:2, 3:5]]  （需导入np库！！！）
或inputs = data.iloc[:, list(range(0,2)) + list(range(3,5))]或data.iloc[:, list(range(0,2)) + [3]+[4]]  (不推荐...感觉好长)

In [4]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  like-value  Alley_Pave  Alley_nan  sale_no  sale_yes  sale_nan
0       4.0         4.5           1          0        0         0         1
1       3.0         4.5           0          1        0         1         0
2       5.0         3.5           0          1        1         0         0
3       4.0         2.0           0          1        0         1         0
4       4.0         2.8           1          0        0         1         0


In [5]:
import torch

X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy())
X, y

(tensor([[4.0000, 4.5000, 1.0000, 0.0000, 0.0000, 0.0000, 1.0000],
         [3.0000, 4.5000, 0.0000, 1.0000, 0.0000, 1.0000, 0.0000],
         [5.0000, 3.5000, 0.0000, 1.0000, 1.0000, 0.0000, 0.0000],
         [4.0000, 2.0000, 0.0000, 1.0000, 0.0000, 1.0000, 0.0000],
         [4.0000, 2.8000, 1.0000, 0.0000, 0.0000, 1.0000, 0.0000]],
        dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000,   2000]))

练习1

In [6]:
# 找出缺失值最多的列名  
# 对 isna() 得到的布尔矩阵按列求和（axis=0，pandas 默认按列聚合）
#按行应该most_na = data.isna(axit=1).sum().idxmax()
most_na = data.isna().sum().idxmax()

# 删除该列（inplace=True 直接在原数据上修改）
data.drop(most_na, axis=1, inplace=True)
print("删除了",most_na)
data


删除了 Alley


NumRooms   Price sale  like-value
0       NaN  127500  NaN         4.5
1       3.0  106000  yes         4.5
2       5.0  178100   no         3.5
3       4.0  140000  yes         2.0
4       NaN    2000  yes         2.8

In [7]:
import numpy as np 
inputs = data.iloc[:, np.r_[0:4]] 
inputs = inputs.fillna(inputs.mean())
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms   Price  like-value  sale_no  sale_yes  sale_nan
0       4.0  127500         4.5        0         0         1
1       3.0  106000         4.5        0         1         0
2       5.0  178100         3.5        1         0         0
3       4.0  140000         2.0        0         1         0
4       4.0    2000         2.8        0         1         0


练习2

In [8]:
p = torch.tensor(inputs.to_numpy(dtype=float))
p



tensor([[4.0000e+00, 1.2750e+05, 4.5000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00],
        [3.0000e+00, 1.0600e+05, 4.5000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00],
        [5.0000e+00, 1.7810e+05, 3.5000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00],
        [4.0000e+00, 1.4000e+05, 2.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00],
        [4.0000e+00, 2.0000e+03, 2.8000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00]],
       dtype=torch.float64)