In [6]:
import torch
#线性代数知识
#标量
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y,x-y,x/y,x*y,x//y,x**y



(tensor(5.), tensor(1.), tensor(1.5000), tensor(6.), tensor(1.), tensor(9.))

In [8]:
#向量
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [9]:
x[2]

tensor(2)

In [10]:
x.shape

torch.Size([4])

In [12]:
#矩阵
A = torch.arange(20).reshape(5, 4)
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [13]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [14]:
#张量
X = torch.arange(24).reshape(2, 3, 4)
X


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [15]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [16]:
A*B#Hadamard 积（按元素乘法）

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [19]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [20]:
A.shape,A.sum()#等价于A.sum(axis=[0,1]) 降维求和

(torch.Size([5, 4]), tensor(190.))

In [21]:
A_liesum= A.sum(axis=0)#降维求每列长
A_liesum, A_liesum.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [22]:
A_hangsum= A.sum(axis=1)#降维求每行长
A_hangsum, A_liesum.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([4]))

In [23]:
A.mean(), A.sum() / A.numel() #降维平均值

(tensor(9.5000), tensor(9.5000))

In [24]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0] #每列平均值

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [25]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [26]:
sum_A = A.sum(axis=0, keepdims=True)
sum_A

tensor([[40., 45., 50., 55.]])

In [27]:
A / sum_A

tensor([[0.0000, 0.0222, 0.0400, 0.0545],
        [0.1000, 0.1111, 0.1200, 0.1273],
        [0.2000, 0.2000, 0.2000, 0.2000],
        [0.3000, 0.2889, 0.2800, 0.2727],
        [0.4000, 0.3778, 0.3600, 0.3455]])

In [28]:
A.cumsum(axis=0) #按行计算累计总和（每列从上到下依次相加）

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [29]:
#点积 
torch.sum(x * y)

tensor(12.)

In [30]:
#矩阵相乘
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [34]:
u = torch.tensor([3.0, -4.0,-12]) #L2范数 （向量元素平方和的平方根）
torch.norm(u)

tensor(13.)

In [35]:
torch.abs(u).sum()    #L1范数，绝对值函数和按元素求和组合起来。

tensor(19.)

#LP范数 X的绝对值的p次方求和再开p次方根

In [36]:
#矩阵的Frobenius范数
torch.norm(torch.ones((4, 9))) 

tensor(6.)

In [41]:
A=torch.tensor([[2,3,5,7],[8,9,6,5]])
B=A.T
C=B.T
A==C

tensor([[True, True, True, True],
        [True, True, True, True]])

练习1

In [43]:
A=torch.tensor([[2,3,5,7],[8,9,6,5]])
B=torch.ones(2,4)
(A+B).T

tensor([[ 3.,  9.],
        [ 4., 10.],
        [ 6.,  7.],
        [ 8.,  6.]])

In [44]:
A.T+B.T

tensor([[ 3.,  9.],
        [ 4., 10.],
        [ 6.,  7.],
        [ 8.,  6.]])

练习2

In [51]:
A=torch.tensor([[2,3],[8,9]])
print(A)
print(A.T)
A+A.T



tensor([[2, 3],
        [8, 9]])
tensor([[2, 8],
        [3, 9]])


tensor([[ 4, 11],
        [11, 18]])

练习3
总是对称的 

AT+A=(AT+A)T=A+AT

In [52]:
X = torch.arange(24).reshape(2, 3, 4)
len(X)

2

练习4 练习5
4  结果是2 对应X轴即第一个维度的值
5  是的 这个轴是最外层维度（第 0 轴）

In [65]:
A = torch.arange(6).reshape(2,3)

A/A.sum(axis=1,keepdim=True)


tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

练习6
A/A.sum(axis=1)会报错 因为张量形状不匹配。无法触发广播机制
广播机制有条件，并不是无限制兼容维度不匹配，仅允许「尾部维度相等」或「尾部维度有 1」的情况；

In [95]:
A = torch.arange(24).reshape(3, 2, 4)
print(A)
print()
print( A.sum(axis=0))
print( A.sum(axis=1))
print( A.sum(axis=2))

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])

tensor([[24, 27, 30, 33],
        [36, 39, 42, 45]])
tensor([[ 4,  6,  8, 10],
        [20, 22, 24, 26],
        [36, 38, 40, 42]])
tensor([[ 6, 22],
        [38, 54],
        [70, 86]])


练习7

In [108]:
x = torch.arange(12, dtype=torch.float32).reshape(2, 2, 3)
print(x)
# 默认行为：计算整个张量的L2范数（标量）
a1 = torch.linalg.norm(x)
print(a1)

# 指定维度：在第0，第1和第3上计算L2范数
y0 = torch.linalg.norm(x, dim=0)
y1 = torch.linalg.norm(x, dim=1)
y2 = torch.linalg.norm(x, dim=2)
print(y0,y0.shape)
print(y1,y1.shape)
print(y2,y2.shape)


# 计算L1范数
# 在第0，第1和第2轴上计算L1范数
l1_0 = torch.linalg.norm(x,ord=1,dim=0)
l1_1 = torch.linalg.norm(x,ord=1,dim=1)
l1_2 = torch.linalg.norm(x,ord=1,dim=2)
print(l1_0)
print(l1_1)
print(l1_2)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
tensor(22.4944)
tensor([[ 6.0000,  7.0711,  8.2462],
        [ 9.4868, 10.7703, 12.0830]]) torch.Size([2, 3])
tensor([[ 3.0000,  4.1231,  5.3852],
        [10.8167, 12.2066, 13.6015]]) torch.Size([2, 3])
tensor([[ 2.2361,  7.0711],
        [12.2066, 17.3781]]) torch.Size([2, 2])
tensor([[ 6.,  8., 10.],
        [12., 14., 16.]])
tensor([[ 3.,  5.,  7.],
        [15., 17., 19.]])
tensor([[ 3., 12.],
        [21., 30.]])


练习8
torch.linalg.norm(x,ord=1,dim=0)  ord默认=2 dim默认None(计算整个张量的范数)
ord = 1 计算对应的L1范数
